server:
  port: 8080
  context-path: /
  forward-headers-strategy: framework


spring:
  application:
    name: booking-service

  datasource:
    url: jdbc:mysql://switchback.proxy.rlwy.net:52890/railway?useSSL=false&serverTimezone=UTC
    username: root
    password: TNNXlnWSrFPdBECuGMeoVuwtKkIywlFM

  jpa:
    hibernate:
      ddl-auto: update

  servlet:
    multipart:
      enabled: true
      max-file-size: 5MB
      max-request-size: 25MB
      file-size-threshold: 2KB

  mail:
    default-encoding: UTF-8
    host: smtp.larksuite.com
    username: notification@blwsmartware.net
    password: XgZC3ehR2k6db30U
    port: 465
    protocol: smtp
    test-connection: false
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true
      mail.smtp.ssl.enable: true

  security:
    oauth2:
      success-redirect-url: https://hotel.trantuanhiep.site/auth/oauth2/success
      client:
        registration:
          google:
            client-id: 190811063148-vjjppcp0ne4f82i0jlcup8dp413id3q6.apps.googleusercontent.com
            client-secret: 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
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            scope:
              - openid
              - email
              - profile
            authorization-grant-type: authorization_code
            client-name: Google
        provider:
          google:
            authorization-uri: https://accounts.google.com/o/oauth2/v2/auth
            token-uri: https://oauth2.googleapis.com/token
            user-info-uri: https://www.googleapis.com/oauth2/v2/userinfo
            user-name-attribute: email

jwt:
  secret: JWT_SECRET_KEY_MUST_BE_32_DIGITS
  expiration-minutes: 30
  expiration-day: 90

config:
  cloudinary_name: dvmzhu5ra
  cloudinary_key: 613489846624929
  cloudinary_secret: r717QEtgHZPiBqlUZ02m9gq26Vg

  cors: https://hotel.trantuanhiep.site
  file:
    upload-dir: /tmp/uploads
  admin:
    name: adminadmin
    password: adminadmin123
    email: adminadmin@blwsmartware.net
    username: adminadmin

vnpay:
  tmnCode: ZN9VA6NB
  secretKey: SZ6FAO4WYDQE2B33L2Q1M8O3OJRHLDT9
  paymentUrl: https://sandbox.vnpayment.vn/paymentv2/vpcpay.html
  apiUrl: https://sandbox.vnpayment.vn/merchant_webapi/api/transaction
  returnUrl: https://hotel.trantuanhiep.site/payment/return
  ipnUrl: https://hotel-booking-be-zdtg.onrender.com/api/payment/vnpay/ipn
